server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki_container:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'task-service'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'task-service'
          app: 'taskflow'
          __path__: /path/to/logs/*.log